In [ ]:
# Install the necessary libraries
!pip install datasets pandas -q

In [ ]:
from datasets import load_dataset
import pandas as pd

# 1. Load the dataset using the Hugging Face library
dataset = load_dataset("fka/awesome-chatgpt-prompts", split="train")

# 2. Convert to a Pandas DataFrame
# A DataFrame (often named 'df') is a 2-dimensional table with rows and columns.
df_prompts = dataset.to_pandas()

# 3. Print the original length using the len() function
print("Original row count:", len(df_prompts))

# 4. Remove duplicate rows
# The drop_duplicates method looks at the 'prompt' column and keeps only the first occurrence.
df_clean = df_prompts.drop_duplicates(subset=['prompt'])

# 5. Print the new length
print("Cleaned row count:", len(df_clean))

# 6. Display the first 5 rows using the head() method
display(df_clean.head())

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

prompts.csv: 0.00B [00:00, ?B/s]

Generating train split: 0 examples [00:00, ? examples/s]

Original row count: 1559
Cleaned row count: 1557

,act,prompt,for_devs,type,contributor
0,Ethereum Developer,Imagine you are an experienced Ethereum develo...,True,TEXT,ameya-2003
1,Linux Terminal,I want you to act as a linux terminal. I will ...,True,TEXT,f
2,English Translator and Improver,"I want you to act as an English translator, sp...",False,TEXT,f
3,Job Interviewer,I want you to act as an interviewer. I will be...,False,TEXT,"f,iltekin"
4,JavaScript Console,I want you to act as a javascript console. I w...,True,TEXT,omerimzali

In [ ]:
from datasets import load_dataset
import pandas as pd

# 1. Load the dataset
dataset_rt = load_dataset("rotten_tomatoes", split="train")
df_movies = dataset_rt.to_pandas()

# 2. Filter out short text
# df_movies['text'].str.len() calculates the character count of each row.
# >= 30 creates a True/False filter.
# The outer df_movies[...] applies the filter to keep only the True rows.
df_filtered = df_movies[df_movies['text'].str.len() >= 30].copy()

# 3. Rename numerical labels to text
# A Python Dictionary {} maps keys to values. Here, 0 maps to "negative".
label_mapping = {0: "negative", 1: "positive"}
df_filtered['sentiment'] = df_filtered['label'].map(label_mapping)

# 4. View the updated data
display(df_filtered[['text', 'label', 'sentiment']].head())

README.md: 0.00B [00:00, ?B/s]

train.parquet:   0%|          | 0.00/699k [00:00<?, ?B/s]

validation.parquet:   0%|          | 0.00/90.0k [00:00<?, ?B/s]

test.parquet:   0%|          | 0.00/92.2k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/8530 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/1066 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1066 [00:00<?, ? examples/s]

                                                text  label sentiment
0  the rock is destined to be the 21st century's ...      1  positive
1  the gorgeously elaborate continuation of " the...      1  positive
2                     effective but too-tepid biopic      1  positive
3  if you sometimes like to go to the movies to h...      1  positive
4  emerges as something rare , an issue movie tha...      1  positive

In [ ]:
from datasets import load_dataset
import pandas as pd

# 1. Load the dataset
dataset_dolly = load_dataset("databricks/databricks-dolly-15k", split="train")
df_dolly = dataset_dolly.to_pandas()

# 2. Define the formatting function
def format_templates(row):
    instruction = row['instruction']
    response = row['response']

    # f-strings allow us to inject variables inside curly brackets {}. \n creates a line break.

    # Gemma Format
    gemma = f"<start_of_turn>user\n{instruction}<end_of_turn>\n<start_of_turn>model\n{response}<end_of_turn>"

    # Llama 3 Format
    llama3 = f"<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\n{instruction}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n{response}<|eot_id|>"

    # Return as a Pandas Series so it creates two separate columns
    return pd.Series([gemma, llama3])

# 3. Apply the function to the DataFrame
df_dolly[['gemma_formatted', 'llama3_formatted']] = df_dolly.apply(format_templates, axis=1)

# 4. Print to compare the differences!
print("--- GEMMA FORMAT ---")
print(df_dolly['gemma_formatted'].iloc[0])
print("\n--- LLAMA 3 FORMAT ---")
print(df_dolly['llama3_formatted'].iloc[0])

README.md: 0.00B [00:00, ?B/s]

databricks-dolly-15k.jsonl:   0%|          | 0.00/13.1M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/15011 [00:00<?, ? examples/s]

--- GEMMA FORMAT ---
<start_of_turn>user
When did Virgin Australia start operating?<end_of_turn>
<start_of_turn>model
Virgin Australia commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route.<end_of_turn>

--- LLAMA 3 FORMAT ---
<|begin_of_text|><|start_header_id|>user<|end_header_id|>

When did Virgin Australia start operating?<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Virgin Australia commenced services on 31 August 2000 as Virgin Blue, with two aircraft on a single route.<|eot_id|>